### ISSUE TITLE
Préparer l'application à la mise en production

### ISSUE THREAD

**Issue by MAXOUXAX** [datsmysong/app#12]
Les différentes pages suivantes doivent être intégrées en suivant les maquettes:

- [x] datsmysong/app-legacy#134
- [x] datsmysong/app-legacy#135
- [x] datsmysong/app-legacy#136
- [x] datsmysong/app-legacy#137
- [x] datsmysong/app-legacy#138
- [ ] datsmysong/app#13
- [x] datsmysong/app-legacy#146
