### ISSUE TITLE
Création de compte à partir d'un compte Spotify

### ISSUE THREAD

**Issue by MAXOUXAX** [datsmysong/app#2]
# TODO 
- [x] Page d’inscription avec le squelette
- [x] Bouton connection avec Spotify
- [x] Appel à notre backend
> - [x] Register avec Supabase Auth avec le provider
> - [x] Demander les infos permettant de mettre à jour la table user_profil & profil
